# how to run:
# ansible-playbook findtags.yml -e ec2roles=facetedsearch -e env=test -e EC2_REGION=us-west-2 -i /etc/ansible/ec2.py
---
- name: EC2 Tag Searching
  hosts: localhost
  gather_facts: false
  tasks:
  - name: Gather hosts matching tags. This is important.
    ec2_instance_facts:
      region: "{{ EC2_REGION }}"
      filters:
        "tag:Roles": "{{ ec2roles }}"
        "tag:ENV": "{{ env }}"
    register: tagged_instances

#  - Name: Just the facts
#    set_fact:
#     iids: "{{ tagged_instances.instance_id | map(attribute='id') | list }}"

  - debug:
      msg: "this one {{ item }}"
    with_items:
        - "{{ tagged_instances.instances | map(attribute='instance_id') | list }}"
