---
- hosts: localhost

  tasks:
  - name: Get Primary VPC
    register: pri_VPCs
    ec2_vpc_net_facts:
      region: "{{ pri_EC2_REGION }}"
      filters:
        "tag:Name": "{{pri_VPC_TAG}}"

  - name: Write VPC file
    copy:
      content: "{{ pri_VPCs.vpcs }}"
      dest: "{{ outdir }}/{{pri_VPC_TAG}}_facts"
      
  - name: estalish VPC ID as fact
    set_fact:
     vpcid: "{{ pri_VPCs.vpcs | map(attribute='id') | list }}"

  - debug:
      msg: "The Value of VPCID is {{ vpcid }}"

  - name: Get Subnets
    register: subnets
    ec2_vpc_subnet_facts:
      region: "{{ pri_EC2_REGION }}"
      filters:
        vpc-id: "{{ vpcid }}"

  - name: Write subnet file
    copy:
      content: "{{ subnets.subnets }}"
      dest: "{{ outdir }}/{{pri_VPC_TAG}}_subnetfacts"

  - name: Get Security Groups
    register: sgs
    ec2_group_facts:
      region: "{{ pri_EC2_REGION }}"
      filters:
        vpc-id: "{{ vpcid }}"

  - name: Write security Groups file
    copy: 
      content: "{{ sgs }}"
      dest: "{{ outdir }}/{{pri_VPC_TAG}}_sgfacts"

  - name: Get All NACLs
    register: nacls
    ec2_vpc_nacl_facts:
      region: "{{ pri_EC2_REGION }}"
      filters:
        vpc-id: "{{ vpcid }}"

  - name: Write nacls file
    copy:
      content: "{{ nacls.nacls }}"
      dest: "{{ outdir }}/{{pri_VPC_TAG}}_naclfacts"

  - name: Get Target VPC
    register: sec_VPCs
    ec2_vpc_net_facts:
      region: "{{ sec_EC2_REGION }}"
      filters:
        "tag:Name": "{{sec_VPC_TAG}}"

  - name: Write VPC file
    copy:
      content: "{{ sec_VPCs.vpcs }}"
      dest: "{{ outdir }}/{{sec_VPC_TAG}}_facts"
      
  - name: estalish VPC ID as fact
    set_fact:
     vpcid: "{{ sec_VPCs.vpcs | map(attribute='id') | list }}"

  - debug:
      msg: "The Value of VPCID is {{ vpcid }}"

  - name: Get Subnets
    register: subnets
    ec2_vpc_subnet_facts:
      region: "{{  sec_EC2_REGION }}"
      filters:
        vpc-id: "{{ vpcid }}"

  - name: Write subnet file
    copy:
      content: "{{ subnets.subnets }}"
      dest: "{{ outdir }}/{{sec_VPC_TAG}}_subnetfacts"

  - name: Get Security Groups
    register: sgs
    ec2_group_facts:
      region: "{{  sec_EC2_REGION }}"
      filters:
        vpc-id: "{{ vpcid }}"

  - name: Write security Groups file
    copy: 
      content: "{{ sgs }}"
      dest: "{{ outdir }}/{{sec_VPC_TAG}}_sgfacts"

  - name: Get All NACLs
    register: nacls
    ec2_vpc_nacl_facts:
      region: "{{  sec_EC2_REGION }}"
      filters:
        vpc-id: "{{ vpcid }}"

  - name: Write nacls file
    copy:
      content: "{{ nacls.nacls }}"
      dest: "{{ outdir }}/{{sec_VPC_TAG}}_naclfacts"
